CREATE TABLE MB52_DIARIA (
    CENTRO TEXT,
    NOMBRE_1 TEXT,
    ALMACEN TEXT,
    DENOMINACION_ALMACEN TEXT,
    MATERIAL TEXT,
    TEXTO_BREVE_DE_MATERIAL TEXT,
    STOCK_ESPECIAL TEXT,
    ELEMENTO_PEP TEXT,
    LIBRE_UTILIZACION NUMERIC,
    UNIDAD_MEDIDA_BASE TEXT,
    LOTE TEXT,
    VALOR_LIBRE_UTIL NUMERIC,
    MONEDA TEXT,
    TIPO_MATERIAL TEXT,
    BLOQUEADO NUMERIC,
    VALOR_STOCK_BLOQ NUMERIC,
    STOCK_BLOQUEADO_EM_VALORADO NUMERIC,
    VALSTBLOQUEADO_EM NUMERIC,
    EN_CONTROL_CALIDAD NUMERIC,
    VALOR_EN_INSPCAL NUMERIC,
    STOCK_EN_TRANSITO NUMERIC,
    VALOR_TRANSITO NUMERIC,
    EN_TRASLADO_CENTRO NUMERIC,
    VALOR_EN_TRASLADO NUMERIC,
    DEVOLUCIONES NUMERIC,
    VALSTOCK_BLDEV NUMERIC,
    TRANS_TRASL NUMERIC,
    VALTRANSC_COND NUMERIC,
    STOCK_NO_LIBRE NUMERIC,
    VALOR_NO_LIBRE NUMERIC,
    GRUPO_DE_ARTICULOS TEXT,
    -- Campos automáticos de fecha
    FECHA DATE DEFAULT CURRENT_DATE,
    DIA TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'DD'),
    MES TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'MM'),
    ANIO TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'YYYY'),
    -- Columnas calculadas (no se cargan con COPY)
    TOTAL_CANTIDADES NUMERIC GENERATED ALWAYS AS (
        COALESCE(LIBRE_UTILIZACION,0) +
        COALESCE(BLOQUEADO,0) +
        COALESCE(VALSTBLOQUEADO_EM,0) +
        COALESCE(EN_CONTROL_CALIDAD,0) +
        COALESCE(STOCK_EN_TRANSITO,0) +
        COALESCE(EN_TRASLADO_CENTRO,0) +
        COALESCE(DEVOLUCIONES,0) +
        COALESCE(TRANS_TRASL,0) +
        COALESCE(STOCK_NO_LIBRE,0)
    ) STORED,
    TOTAL_VALORES NUMERIC GENERATED ALWAYS AS (
        COALESCE(VALOR_LIBRE_UTIL,0) +
        COALESCE(VALOR_STOCK_BLOQ,0) +
        COALESCE(STOCK_BLOQUEADO_EM_VALORADO,0) +
        COALESCE(VALOR_EN_INSPCAL,0) +
        COALESCE(VALOR_TRANSITO,0) +
        COALESCE(VALOR_EN_TRASLADO,0) +
        COALESCE(VALSTOCK_BLDEV,0) +
        COALESCE(VALTRANSC_COND,0) +
        COALESCE(VALOR_NO_LIBRE,0)
    ) STORED
);
