CREATE TABLE ME2M_INTERCENTROS (
NOMBRE_PROVEEDOR TEXT,
CENTRO INTEGER,
ALMACEN TEXT,
TIPO_IMPUTACION TEXT,
CLASE_DOC_COMPRAS TEXT,
FECHA_DOCUMENTO_IC DATE,
NUMERO_DOC_COMPRAS_IC NUMERIC,
POSICION_DOC_COMPRAS_IC NUMERIC,
MATERIAL TEXT,
CANT_PEDIDO_IC NUMERIC,
CANT_POR_ENTREGAR_IC NUMERIC,
UNIDAD_MEDIDA_PEDIDO TEXT,
TEXTO_BREVE_DE_MATERIAL TEXT,
NUMERO_NECESIDAD TEXT,
GRUPO_COMPRAS TEXT,
GRUPO_DE_ARTICULOS TEXT,
CENTRO_SUMINISTRADOR TEXT,

    FECHA_CARGUE_ARCHIVO DATE DEFAULT CURRENT_DATE,
    DIA_CARGUE_ARCHIVO TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'DD'),
    MES_CARGUE_ARCHIVO TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'MM'),
    ANIO_CARGUE_ARCHIVO TEXT DEFAULT TO_CHAR(CURRENT_DATE, 'YYYY')
);
