CREATE OR REPLACE VIEW vw_mb25_resumen AS
SELECT
N_RESERVA,
N_POS_RESERVA,
ORDEN,
CENTRO,
ALMACEN,

CASE 
        WHEN ALMACEN IS NULL OR ALMACEN = '' THEN 'GASTOS'
        WHEN ALMACEN = 'H001' THEN 'GASTOS'
        WHEN ALMACEN IN ('G001','G002','G003','E001') THEN 'GASTOS'
        WHEN ALMACEN = 'A001' THEN 'ACTIVO'
        WHEN ALMACEN = 'I001' THEN 'IMPORTADO'
        WHEN ALMACEN IN ('S002','S003') THEN 'SOBRANTE'
		WHEN ALMACEN IN ('P001','P002','P003','P004') THEN 'PROYECTOS'
        ELSE 'OTROS'
    END AS CATEGORIA,
	
MATERIAL,
TEXTO_BREVE_DE_MATERIAL,
UNIDAD_MEDIDA_BASE,
CANT_NECESARIA,
CANT_REDUCIDA,
CANT_DIFERENCIA,
POS_BORRADA,
MOVIMIENTO_PERMITIDO,
SALIDA_FINAL,
FECHA_NECESIDAD,
NOMBRE_USUARIO,
ELEMENTO_PEP,
CENTRO_COSTE,
CLASE_MOVIMIENTO,
STOCK_ESPECIAL,
TEXTO_CLASE_MOVIMIENTO,
LOTE,
CLASE_NECESIDAD,
FECHA_CARGUE_ARCHIVO,
DIA_CARGUE_ARCHIVO,
MES_CARGUE_ARCHIVO,
ANIO_CARGUE_ARCHIVO

FROM MB25_DIARIA;
